### ISSUE TITLE
Default `multiplayer_name` to `APlayerState::PlayerName`

### ISSUE THREAD

**Issue by oberien** [oberien/refunct-tas#123]
If a player hasn't manually set `multiplayer_name` yet, it should default to their steam name. Apparently `APlayerState::PlayerName` is the steam name.

**Comment by LukeSaward1** [comment]
As it turns out, `APlayerState::PlayerName` in fact IS the Steam name.

Here's how to get to it:

- `PlayerState` is in `Controller` which `PlayerController` inherits from.
  Offset: `0x2C8`

- `PlayerName` is in `PlayerState`.
  Offset: `0x2BC`

- FString is just a TArray<T_CHAR>, thus you add an offset for the 0th position in that array.

- Then you should have the Steam name.
