### ISSUE TITLE
Null Cheat Engine pointers upon Pawn spawning/killing

### ISSUE THREAD

**Issue by LukeSaward1** [oberien/refunct-tas#134]
Deleting all code-spawned pawns results in the total nullification of the PersistentLevel.ACharacter pointer and its child pointers, which contains all the pointers regarding the player.

When I spawn a pawn, PlayerCameraManager, MyHUD and CheatManager get nullified.

**Comment by oberien** [comment]
I'm afraid I need to say that your pointer path is incorrect then. What might happen is that the list containing the players gets reallocated because a new player is spawned. If you have the correct pointer path, that shouldn't matter. With the wrong pointer path, all pointers get invalidated when the list gets reallocated.

Nothing I can do about that; you'll need to find a better pointer path.

**Comment by LukeSaward1** [comment]
I can say that the pointer path was acquired through the SDK and Cheat Gear by Ero, resulting in non-changing, perfect pointers.
I'm sure my pointer path isn't an issue here.

**Comment by oberien** [comment]
Apparently needs more investigation

**Comment by LukeSaward1** [comment]
This happens whenever a pawn is spawned: multiplayer, practice...

**Comment by LukeSaward1** [comment]
Update:
I've got no fucking clue what the hell Ero used for the pointers, but I'm sure it does **not** go to LocalPlayers array, which is what should be done.
Will probably have to find + replace all of that shit within the cheat table with `LocalPlayer[0]`.

With that, this is probably a non-issue now.
Closing.
