### ISSUE TITLE
Adding a way to teleport without having to start a "New Game"

### ISSUE THREAD

**Issue by tastymeowmix** [oberien/refunct-tas#59]
I've been trying to find a way to teleport around without having to start a completely new game and I haven't been able to figure out a way to make that happen. I was hoping to get some help in figuring out a way to set this up. Also a simpler way of changing where each different teleport brings you without having to close the game and edit files would also be very nice but I once again don't know how to set that up.

**Comment by oberien** [comment]
Several Ideas here:

You could implement live-reloading of lua files. That way, if you edit and save a lua file, it'll be reloaded into refunct-tas and thus updated. Then you can manually edit a function teleporting you to a location, save the file, and have that directly reflect in-game.

Another idea would be to provide functionality in the HUD to save the current location/position, rotation and level (which button-group you've already pressed) and register (or hardcode) a key to teleport you to your "save point". Something similar to quick-save and quick-load. Position and rotation are easy and already used and implemented for the current teleportbuttons. It might be harder to get the current level. One possibility would be to open the Esc-Menu, which makes the game save its level (and gamestate in general) to a file. Then read and parse that file to get the level from it and call `teleportbuttons` with that level, before setting the position and rotation.
When doing that, it would also make sense to use the load-save functionality of Refunct instead of teleporting you through all the buttons as laid out in https://github.com/oberien/refunct-tas/issues/4#issuecomment-369782125. However, this could become rather complex quite quickly.
Another way to get the current level is through the pointer path used by the autosplitter, which also contains the current level. While we have that for the windows version, I don't know if I ever tried to get the pointer path for the linux version (in fact I don't know which in-game data structures we create the path through, such that I could replicate that on linux).

A limitation of setting the level / teleporting to it is that if there is a level with more than one button, all buttons will be un-pressed, so you can't have a quick-save with some buttons within a level pressed.

**Comment by tastymeowmix** [comment]
Alright thank you I'm definitely going to be looking into getting this set up. No promises I actually know how to do what you laid out here though. Thanks.
